### ISSUE TITLE
OSError: [Errno 2] No such file or directory in get alleles in phases step

### ISSUE THREAD

**Issue by LeiltonLuna** [tobiashofmann88/UCE-data-management#1]
I'm trying to follow the new pipeline to get alleles in phases, but I ended up with an error.

```
> 2018-03-14 16:40:45,526 - phyluce_snp_phase_uces - INFO - ================ Starting phyluce_snp_phase_uces ================
> 2018-03-14 16:40:45,526 - phyluce_snp_phase_uces - INFO - Version: 1.5.0
> 2018-03-14 16:40:45,526 - phyluce_snp_phase_uces - INFO - Argument --bams: /home/auruno/Desktop/Leilton/SECAPR/8_mapping
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --config: /home/auruno/Desktop/Leilton/SECAPR/7_specify_sample_FASTA/phasing.conf
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --conservative: False
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --cores: 3
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --log_path: None
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --output: /home/auruno/Desktop/Leilton/SECAPR/9_phasing_reads
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - Argument --verbosity: INFO
> 2018-03-14 16:40:45,527 - phyluce_snp_phase_uces - INFO - ================ Starting phyluce_snp_phase_uces ================
> 2018-03-14 16:40:45,529 - phyluce_snp_phase_uces - INFO - Getting input filenames and creating output directories
> 2018-03-14 16:40:45,530 - phyluce_snp_phase_uces - INFO - --------------------- Processing hlin_T19779 --------------------
> 2018-03-14 16:40:45,530 - phyluce_snp_phase_uces - INFO - Phasing BAM file for hlin_T19779
> 2018-03-14 16:41:02,957 - phyluce_snp_phase_uces - INFO - Sorting BAM for hlin_T19779
> 2018-03-14 16:41:08,057 - phyluce_snp_phase_uces - INFO - Sorting BAM for hlin_T19779
> 2018-03-14 16:41:13,106 - phyluce_snp_phase_uces - INFO - Creating REF/ALT allele FASTQ file 0
> 2018-03-14 16:42:03,458 - phyluce_snp_phase_uces - INFO - Creating REF/ALT allele FASTQ file 1
> 2018-03-14 16:42:54,992 - phyluce_snp_phase_uces - INFO - Creating REF/ALT allele FASTQ file unphased
> 2018-03-14 16:44:34,833 - phyluce_snp_phase_uces - INFO - Creating REF/ALT allele FASTA file 0 from FASTQ 0
> Traceback (most recent call last):
>   File "/home/auruno/anaconda2/bin/phyluce_snp_phase_uces", line 289, in <module>
>     main()
>   File "/home/auruno/anaconda2/bin/phyluce_snp_phase_uces", line 271, in main
>     fastas = phase_bam(log, individual, reference, bam, args.output)
>   File "/home/auruno/anaconda2/bin/phyluce_snp_phase_uces", line 103, in phase_bam
>     fasta_cons_0 = seqtk.fq_to_fa(log, sample, phasing_out_dir, make_cons_0, "0")
>   File "/home/auruno/anaconda2/lib/python2.7/site-packages/phyluce/seqtk.py", line 40, in fq_to_fa
>     proc = subprocess.Popen(cmd, stdout=seqtk_fasta, stderr=seqtk_out)
>   File "/home/auruno/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/home/auruno/anaconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or `directory``
```
I'm sure this "git" is installed correctly ... anyone know what the problem is?

**Comment by tandermann** [comment]
it seems as if you are running the PHYLUCE phasing script on files generated by the SECAPR pipeline. Make sure you stick with one of these two pipelines as they have different file-formatting and -naming patterns. Follow the SECAPR phasing documentation [here](https://github.com/AntonelliLab/seqcap_processor/blob/3bc70ad3191bc92cdde92ced324bcc0ea8fc1697/docs/notebook/phasing.ipynb) and run the script with `secapr phase_alleles`

**Comment by LeiltonLuna** [comment]
Well ... this is rather strange. I did not install the previous SECAPR. If you noticed the folder in the input file this is just a name I gave.

The above error still persists even though I have updated PHYLUCE. This error occurs on the machines of different colleagues, including Linux and OSX systems.

**Comment by tandermann** [comment]
Ah okay, I was mistaken, I was assuming that based on the name of the input folder.
You should probably post this issue on the PHYLUCE github page (https://github.com/faircloth-lab/phyluce), which Brant Faircloth is maintaining.
He has a better overview over the PHYLUCE code and probably can help with this issue.
This repo here is merely a collection of scripts and tutorials that helps with the analysis of UCE data but you are also welcome to check out our SECAPR pipeline at https://github.com/AntonelliLab/seqcap_processor
